#!/bin/sh /etc/rc.common

START=95

USE_PROCD=1
PROG=/usr/sbin/virtlogd

start_service() {
	mkdir -p /var/log/libvirt/qemu

	procd_open_instance
	procd_set_param command $PROG
	procd_set_param stderr 1
	procd_close_instance
}
